name: flutter_cli_utils
description: A command-line tool that provides useful Flutter utilities.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.0
  mason_logger: ^0.2.15
  pub_updater: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0

executables:
  fcu: flutter_cli_utils
