# Fastfile for Android deployment

default_platform(:android)

platform :android do
  desc "Deploy to Google Play Internal Testing"
  lane :internal do |options|
    upload_to_play_store(
      aab: options[:aab],
      json_key: options[:json_key],
      track: 'internal',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true
    )
  end

  desc "Deploy to Google Play Beta"
  lane :beta do |options|
    upload_to_play_store(
      aab: options[:aab],
      json_key: options[:json_key],
      track: 'beta',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true
    )
  end

  desc "Deploy to Google Play Production"
  lane :production do |options|
    upload_to_play_store(
      aab: options[:aab],
      json_key: options[:json_key],
      track: 'production',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true
    )
  end
end
