name: {{proj_name}}
description: {{proj_desc}}
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/common/
  fonts: # TODO({{dev_name}}): use your own fonts if needed
    - family: consolas
      fonts:
        - asset: assets/fonts/consolas.ttf
        - asset: assets/fonts/consolas_bold.ttf
          weight: 700
