/// Analyzer plugin enforcing Flutter architecture boundaries.
///
/// This plugin provides lint rules that enforce architectural constraints
/// for Flutter projects generated by Flutter CLI Utils (FCU).
///
/// Rules enforce:
/// - Feature isolation (no cross-feature imports)
/// - The barrel as the only door (no direct src/ imports)
/// - Layer boundaries (foundation, features, resources, router, app)
/// - Composition roots (dependency_injection, fake_data)
/// - Entry point restrictions (main_common.dart, main_*.dart files)
library;

import 'package:analysis_server_plugin/plugin.dart';
import 'package:analysis_server_plugin/registry.dart';

import 'package:architecture_lint_rules/src/rules/app_import_restrictions_rule.dart';
import 'package:architecture_lint_rules/src/rules/dependency_injection_import_restrictions_rule.dart';
import 'package:architecture_lint_rules/src/rules/fake_data_import_restrictions_rule.dart';
import 'package:architecture_lint_rules/src/rules/features_import_restrictions_rule.dart';
import 'package:architecture_lint_rules/src/rules/foundation_import_restrictions_rule.dart';
import 'package:architecture_lint_rules/src/rules/main_common_import_restrictions_rule.dart';
import 'package:architecture_lint_rules/src/rules/main_environment_files_import_restrictions_rule.dart';
import 'package:architecture_lint_rules/src/rules/no_feature_cross_imports_rule.dart';
import 'package:architecture_lint_rules/src/rules/no_src_imports_rule.dart';
import 'package:architecture_lint_rules/src/rules/resources_cannot_import_rule.dart';
import 'package:architecture_lint_rules/src/rules/router_import_restrictions_rule.dart';

/// Top-level plugin variable - REQUIRED by Analysis Server.
///
/// The Analysis Server looks for a variable named `plugin` in lib/main.dart.
final plugin = ArchitectureLintPlugin();

/// Plugin implementation for architecture lint rules.
class ArchitectureLintPlugin extends Plugin {
  @override
  String get name => 'architecture_lint_rules';

  @override
  void register(PluginRegistry registry) {
    // Register all rules as warning rules (enabled by default).
    // This ensures architectural violations are caught immediately.
    registry.registerWarningRule(NoFeatureCrossImportsRule());
    registry.registerWarningRule(NoSrcImportsRule());
    registry.registerWarningRule(ResourcesCannotImportRule());
    registry.registerWarningRule(FoundationImportRestrictionsRule());
    registry.registerWarningRule(FeaturesImportRestrictionsRule());
    registry.registerWarningRule(RouterImportRestrictionsRule());
    registry.registerWarningRule(AppImportRestrictionsRule());
    registry.registerWarningRule(DependencyInjectionImportRestrictionsRule());
    registry.registerWarningRule(FakeDataImportRestrictionsRule());
    registry.registerWarningRule(MainCommonImportRestrictionsRule());
    registry.registerWarningRule(MainEnvironmentFilesImportRestrictionsRule());
  }
}
